import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={inter.className}>
        <main>
          <nav style={{backgroundColor:'purple',textAlign:'center'}}>
            <Link href="/" style={{margin:50}}>
              Home
            </Link>
            <Link href="/list">
              ADD
            </Link>
          </nav>
        </main>
        {children}
        </body>
    </html>
    </ClerkProvider>
    
  )
}
